### ISSUE TITLE
NLPTOFHIR Annotator Error

### ISSUE THREAD

**Issue by RokshanJ** [BD2KOnFHIR/NLP2FHIR#13]
@qqndrew I am getting this error while running Annotator main class

Exception in thread "main" org.apache.uima.resource.ResourceInitializationException: Invalid value for parameter "InputDirectory" in component "edu.mayo.bsi.nlp2fhir.preprocessors.FHIRXMIFileSystemReader" -- directory "xmis" does not exist.
	at org.apache.ctakes.core.cr.XmiCollectionReaderCtakes.initialize(XmiCollectionReaderCtakes.java:81)
	at org.apache.uima.collection.CollectionReader_ImplBase.initialize(CollectionReader_ImplBase.java:70)
	at org.apache.uima.impl.CollectionReaderFactory_impl.produceResource(CollectionReaderFactory_impl.java:103)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:331)
	at org.apache.uima.UIMAFramework.produceCollectionReader(UIMAFramework.java:812)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:133)
	at edu.mayo.bsi.nlp2fhir.Pipeline.main(Pipeline.java:114)

**Comment by qqndrew** [comment]
This error typically suggests that the directory parameter you supplied for input does not exist.
